In [1]:
import cv2
import numpy as np

**Load/Read image**

In [2]:
img = cv2.imread('Modi.jpg', 1)

**Let's take a closer look at how images are stored**

In [3]:
print(img)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


**Shape gives the dimensions of the image array**

In [4]:
img.shape

(1358, 1500, 3)

**Display the image**

In [5]:
cv2.imshow('Prime minster of INDIA', img)

cv2.waitKey(2000)

cv2.destroyAllWindows()

In [6]:
img = cv2.imread('Modi.jpg')
cv2.imshow('PM',img)
cv2.waitKey()
cv2.destroyAllWindows()

**Saving Image**

In [7]:
cv2.imwrite('modi_n_img.jpg',img)

True

**Resize Image**

In [8]:
img = cv2.imread('Modi.jpg')
resize_image = cv2.resize(img,(360,400))
BWImg = cv2.cvtColor(resize_image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Modi Image',BWImg)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
img.shape[0]*0.5

679.0

In [10]:
img.shape[1]*0.5

750.0

**Face Detection using HAAR Cascade Classifiers**

In [11]:
# We point OpenCV's CascadeClassifier function to where our classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale
image = cv2.imread('Modi.jpg')

image = cv2.resize(img,(500,500))
BWImg = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

### Tuning Cascade Classifiers - detectMultiScale(input image, **Scale Factor**, **Min Neighbors**)
faces = face_classifier.detectMultiScale(BWImg, 1.05, 5)

In [12]:
print(faces)

[[205  79 217 217]]


In [13]:
# We point OpenCV's CascadeClassifier function to where our classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale

image = cv2.imread('Modi.jpg')
image = cv2.resize(image, (500,500))
BWImg = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

## Tuning Cascade Classifiers - detectMultiScale(input image, **Scale Factor**, **Min Neighbors**)
faces = face_classifier.detectMultiScale(BWImg, 1.05, 5)

# Scale Factor - Specifies how much we reduce the image size each time we scale.
# E.g. in facce detection we typically use 1.3. This means we reduce the image by 30% each time it's scaled.
# Smaller values, like 1.05 will take Longer to compute, but will increase the rate of detection.

## Min Neighbors**
# Specifies the number of neighbous each potential window should have in order to consider it a positive detection.
# Typically set between 3-6.
# It acts as sensitivity setting, low values will sometimes detect multiples faces over a single faces
# High values will ensure less false positives, but you may miss some faces.


In [14]:
print(faces)

[[205  79 217 217]]


In [15]:
# We point OpenCV's CascadeClassifier function to where our classifier (XML file format) is stored
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale
image = cv2.imread('Modi.jpg')
image = cv2.resize(image, (500,500))
BWImg = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(BWImg, 1.05,5)

if faces is ():
    print("No face fund")


for (x,y,w,h) in faces:
    cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,100), 1)

cv2.imshow('Face Detection', image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Saurav Kumar\AppData\Local\Temp\ipykernel_17404\79947844.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


**Face & Eye Detection using HAAR Cascade Classifiers in Image**

In [16]:
face_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

img = cv2.imread('Modi.jpg')
resize_image = cv2.resize(img,(500,500))
BWImg = cv2.cvtColor(resize_image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(BWImg, 1.03,5)

# When no faces detected, face_classifier returns and empty tuple

if faces is ():
    print('No faces found')

for (x,y,w,h) in faces:
    cv2.rectangle(resize_image,(x,y),(x+w, y+h),(255,0,0),2)
    roi_gray = BWImg[y:y+h, x:x+w]
    roi_color = resize_image[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex, ey, ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew, ey+eh),(0,255,0),2)


cv2.imshow('img', resize_image)
cv2.waitKey(0)

cv2.destroyAllWindows()

<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Saurav Kumar\AppData\Local\Temp\ipykernel_17404\336807789.py:12: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


**Capture a video**

In [17]:
import cv2
video = cv2.VideoCapture(0)
while True:
    check, frame = video.read()
    BWImg = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
    cv2.imshow('Video',frame)
    if cv2.waitKey(1) == ord('q'):
        break

    video.release()
    cv2.destroyAllWindows()



error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [ ]:


face_cascade = cv2.CascadeClassifier('Haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('Haarcascades/haarcascade_eye.xml')

def detect(BWImg, frame):
    faces = face_cascade.detectMultiScale(BWImg,1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = BWImg[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 3)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey), (ex+ew, ey+eh),(0,255,0),2)
        return frame

#Doing some Face Recognition with the webcam

video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    BWImg = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(BWImg, frame)
    cv2.imshow('video', canvas)
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()
    

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:967: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
